# Generated by Django 5.1.6 on 2025-03-05 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=250, null=True)),
                ('ticket_id', models.CharField(max_length=36, null=True)),
                ('status', models.CharField(max_length=12, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
